# Generated by Django 2.2.3 on 2020-07-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
