# Generated by Django 2.2.3 on 2020-08-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDonor', '0003_organisation_orgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
